---
title: "Faktaark"

output:
  html_document:
    toc: true
    toc_depth: 6
    toc_float: true
    
    
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'faktaark.html'))})
 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[Hjem](https://ninanor.github.io/IBECA) | 
[Økosystem Fjell](https://ninanor.github.io/IBECA/fjell) |
[Faktaark](https://ninanor.github.io/IBECA/faktaark) |



## Faktaark
```{r, echo=FALSE, message=F}
library(readxl)
library(knitr)
library(kableExtra)
library(dplyr)
doc <- read_excel("data/dokumentasjonIndikatorer.xlsx")
```

```{r, echo=F}
for(i in 1:nrow(doc)){
  docTemp <- doc[i,]
  docTemp <- as.data.frame(t(docTemp))
  out <- kableExtra::kable(docTemp, "html",
        caption = paste("Metadatasjekama for tilstandindikatoren ", 
                        docTemp$V1[1]), col.names = NULL) %>%
  kableExtra::kable_styling(full_width = T)%>%         # not working
  column_spec(1, width = "1cm")       # not working
  assign(docTemp$V1[1], out)
}

```

### Bestandsnivå Fjellrev

```{r, echo=FALSE}
tbl <- get('Bestandsnivå fjellrev')
tbl

```


### Bestandsnivå Jerv

```{r, echo=FALSE}
tbl <- get('Bestandsnivå jerv')
tbl

```




Last update:
```{r}
Sys.time()
```

