---
title: "Engelske figurer side 4"

output:
  html_document:
    toc: false
    toc_depth: 3
    toc_float: true
    
    
knit: (function(input_file, encoding) {
  out_dir <- '../docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'engelskeFigurer4.html'))})
 
---

Forsettelse fra engelskeFigurer.Rmd.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Packages
library(dplyr)
library(tidyr)

library(raster)
library(Hmisc)
library(tidyverse)

```

# Klimavariabler

Skriptet ligger her: P:\41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly\FINAL\Scripts\Indicators\as_txt_files_5_April_2021

Med regioner

```{r}
### 3. Plot summary output

# First check and fix some basic data for plotting
#rm(list=ls())
library(raster)
library(Hmisc)
library(tidyverse)

setwd("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Raw_data/Klima")

folders_climate <- list.files()
folders_climate <- folders_climate[folders_climate!="Readme_Klima.txt"]
folders_climate <- folders_climate[folders_climate!="oversikt_pre_calcs.xlsx"]

variables_climate <- data.frame(folders_climate)
variables_climate$folders_climate <- sub(" and Forest Pixel Count", "", variables_climate$folders_climate)

variables_climate$order <- c(1,3,2,6,4,5,7) # order as in tablefiles
variables_climate <- variables_climate[order(variables_climate$order),]

#Region 1 = nord Norge, Region 2 = midt Norge, Region 3 = Øst norge, Region 4 = vest Norge, Region 5 = sør-Norge
regions <- data.frame(ord = c(2,1,4,6,5,3))
regions$navn <- c("Nord-Norge", "Midt-Norge", "Østlandet", "Vestlandet", "Sørlandet", "Norge")
regions <- regions[order(regions$ord),]

#################

# Files to read
path <- ("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Additional_data/Tables/regr")
tablefiles <- list.files(path = path, pattern=".csv")

tablefiles <- tablefiles[grep("*_slope*",tablefiles,invert=TRUE)]

#tablefiles <- sub("?", "over", tablefiles, fixed=T)

# Set colour codes
colours <- c(rep(c("#7A9A01", "#93328E", "dark grey", "#FFB25B", "#2DCCD3","#004F71"), length(tablefiles)/6))
regions$colours <- colours[1:6]
regions$ord2 <- c(5,6,1,2,3,4)

# Set max/min data for plots
val_dat <- data.frame(var = tablefiles,
                      max = c(rep(60,6),rep(50,6),rep(50,6),rep(5,6),rep(10,6),rep(50,6),rep(600,6)),
                      min = c(rep(-60,6),rep(-50,6),rep(-80,6),rep(-5,6),rep(-10,6),rep(-50,6),rep(-600,6)))

path <- "../output/paavirkningsindikatorer/englishPlots/skog/with region/"
path2 <- "P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Additional_data/Tables/regr/"

variables_climate$axisLabels <- c(
  "Days with Precipitation",
  "Days with Snow Cover  and > 0\u00B0C",
  "Days with Snow Cover",
  "Mean Summer Temperature (\u00B0C)",
  "Mean Winter Temperature (\u00B0C)",
  "Length of Growing Season",
  "Annual Precipitation (mm)"
)

# Loop for each variable to save png files
for(j in 1:7){
  png(paste(path, variables_climate$folders_climate[j], ".png", sep=""), res=300, units="in", height=6, width=8)
  
  par(mar=c(4,6,4,1))
  
  for(i in ((j-1)*6+1):(j*6)) {
    

    x_all <- read.csv(paste0(path2, tablefiles[i]), header=T)
    x_all <- x_all[x_all$year>1960,]
    file_x <- gsub("(\u00B0C)", "", tablefiles[i])
    file_x <- gsub(" > ", "", file_x)
    
    #str_split(tablefiles[i], "_", simplify = TRUE)[1]
    
    if (i==1|i==7|i==13|i==19|i==25|i==31|i==37){
      plot(x_all$wm1~x_all$year, frame=FALSE, ylim=c(val_dat$min[i], val_dat$max[i]),
           type="n",
           ylab=paste(variables_climate$axisLabels[i],
             #paste(gsub("regr","",str_split(tablefiles[i], "_", simplify = TRUE)[1])),
                      "- anomalies compared to 1961-1990 baseline", sep="\n"), xlab="")

      abline(h=0, col="black", lty=1, lwd=1)
      
      lines(x_all$year, x_all$wm1, col=colours[i], lwd=1.5, lty=1) 
      
    } else {
      
      lines(x_all$year, x_all$wm1, col=colours[i], lwd=1.5, lty=1) 
      
    }
    
  }
  
  legend("top", legend = regions$navn[order(regions$ord2)], col = regions$colours[order(regions$ord2)],  
         lwd=1.5, lty=1, 
         bty="n", inset=0, title="", horiz = TRUE,
         cex=0.7)
  dev.off()
 
}

```


Uten regioner

```{r}
### 3. Plot summary output

# First check and fix some basic data for plotting
#rm(list=ls())
library(raster)
library(Hmisc)
library(tidyverse)

setwd("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Raw_data/Klima")

folders_climate <- list.files()
folders_climate <- folders_climate[folders_climate!="Readme_Klima.txt"]
folders_climate <- folders_climate[folders_climate!="oversikt_pre_calcs.xlsx"]

variables_climate <- data.frame(folders_climate)
variables_climate$folders_climate <- sub(" and Forest Pixel Count", "", variables_climate$folders_climate)

variables_climate$order <- c(1,3,2,6,4,5,7) # order as in tablefiles
variables_climate <- variables_climate[order(variables_climate$order),]

#Region 1 = nord Norge, Region 2 = midt Norge, Region 3 = Øst norge, Region 4 = vest Norge, Region 5 = sør-Norge
regions <- data.frame(ord = c(2,1,4,6,5,3))
regions$navn <- c("Nord-Norge", "Midt-Norge", "Østlandet", "Vestlandet", "Sørlandet", "Norge")
regions <- regions[order(regions$ord),]

#################

# Files to read
path <- ("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Additional_data/Tables/regr")
tablefiles <- list.files(path = path, pattern=".csv")

tablefiles <- tablefiles[grep("*_slope*",tablefiles,invert=TRUE)]

#tablefiles <- sub("?", "over", tablefiles, fixed=T)

# Set colour codes
colours <- c(rep(c("#7A9A01", "#93328E", "dark grey", "#FFB25B", "#2DCCD3","#004F71"), length(tablefiles)/6))
regions$colours <- colours[1:6]
regions$ord2 <- c(5,6,1,2,3,4)

# Set max/min data for plots
val_dat <- data.frame(var = tablefiles,
                      max = c(rep(60,6),rep(50,6),rep(50,6),rep(5,6),rep(10,6),rep(50,6),rep(600,6)),
                      min = c(rep(-60,6),rep(-50,6),rep(-80,6),rep(-5,6),rep(-10,6),rep(-50,6),rep(-600,6)))

path <- "../output/paavirkningsindikatorer/englishPlots/skog/"
path2 <- "P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Additional_data/Tables/regr/"

variables_climate$axisLabels <- c(
  "Days with Precipitation",
  "Days with Snow Cover  and > 0\u00B0C",
  "Days with Snow Cover",
  "Mean Summer Temperature (\u00B0C)",
  "Mean Winter Temperature (\u00B0C)",
  "Length of Growing Season",
  "Annual Precipitation (mm)"
)

tablefiles <- tablefiles[grep("_Norge", tablefiles)]
val_dat <- val_dat[grep("_Norge", val_dat$var),]


# Loop for each variable to save png files
for(j in 1:7){
  png(paste(path, variables_climate$folders_climate[j], ".png", sep=""), res=300, units="in", height=6, width=8)
  
  par(mar=c(4,6,4,1))
  


    x_all <- read.csv(paste0(path2, tablefiles[j]), header=T)
    x_all <- x_all[x_all$year2>1960,]
    file_x <- gsub("(\u00B0C)", "", tablefiles[j])
    file_x <- gsub(" > ", "", file_x)
    
    #str_split(tablefiles[i], "_", simplify = TRUE)[1]
    
  plot(x_all$wm2~x_all$year2, frame=FALSE, ylim=c(val_dat$min[j], val_dat$max[j]),
           type="n",
           ylab=paste(variables_climate$axisLabels[j],
             #paste(gsub("regr","",str_split(tablefiles[i], "_", simplify = TRUE)[1])),
                      "- anomalies compared to 1961-1990 baseline", sep="\n"), xlab="")

      abline(h=0, col="grey", lty=1, lwd=1)
      
      lines(x_all$year2, x_all$wm2, col="black", lwd=2, lty=1) 
      
  
  #legend("top", legend = regions$navn[order(regions$ord2)], col = regions$colours[order(regions$ord2)],  
  #       lwd=1.5, lty=1, 
  #       bty="n", inset=0, title="", horiz = TRUE,
  #       cex=0.7)
  dev.off()
 
}


# Combined
# remove one variable
tablefiles <- tablefiles[-2]
val_dat <- val_dat[-2,]
val_dat$max <- c(35,  10,   3,  6,  40, 200)
val_dat$min <- c(-25,  -25,   -2,  -5,  -20, -200)

variables_climate <- variables_climate[-2,]
# Loop for each variable to save png files

png(paste(path, "Combined Climate Figures", ".png", sep=""), res=300, units="in", height=6, width=8)
par(mfrow=c(2,3),mar=c(4,6,4,1))

for(j in 1:6){
  
  

  


    x_all <- read.csv(paste0(path2, tablefiles[j]), header=T)
    x_all <- x_all[x_all$year2>1960,]
    file_x <- gsub("(\u00B0C)", "", tablefiles[j])
    file_x <- gsub(" > ", "", file_x)
    
  plot(x_all$wm2~x_all$year2, frame=FALSE, ylim=c(val_dat$min[j], val_dat$max[j]),
           type="n",
           ylab=
         #paste(
         variables_climate$axisLabels[j],
             #paste(gsub("regr","",str_split(tablefiles[i], "_", simplify = TRUE)[1])),
             #"- anomalies compared to 1961-1990 baseline", 
       #sep="\n"), 
       xlab="")

      abline(h=0, col="grey", lty=1, lwd=1)
      
      lines(x_all$year2, x_all$wm2, col="black", lwd=2, lty=1) 
      
  
  
 
 
}
dev.off()
```

