---
title: "Engelske figurer side 2"

output:
  html_document:
    toc: false
    toc_depth: 3
    toc_float: true
    
    
knit: (function(input_file, encoding) {
  out_dir <- '../docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'engelskeFigurer2.html'))})
 
---

Forsettelse fra engelskeFigurer.Rmd


Fortsetter med skograpporten og indikatorfigurene der.

Fra indicator_plots.R skal jeg lage nye figurer for et utvalg variabler.

# Indicator_plots



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Packages
library(dplyr)
library(tidyr)

```

```{r}
# Set resolution
resout <- 300
```

##NI
```{r, warning=F}
setwd("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Indicator_values/Forest")
### Nature index indicators
forest <- read.csv("forestsamp.csv", header=T,  row.names = 1)
mpred <- read.csv("Index_Mellompredator.csv", header=T,  row.names = 1)
tpred <- read.csv("Index_Topp-predator.csv", header=T,  row.names = 1)
nedbr <- read.csv("Index_Nedbryter.csv", header=T,  row.names = 1)
herbi <- read.csv("Index_Plante- og filterspisere.csv", header=T,  row.names = 1)
primp <- read.csv("Index_Primærprodusent.csv", header=T,  row.names = 1)

```


Combine
```{r}

forest$X <- "Nature Index Forest"
mpred$X  <- "Meso-predators"
tpred$X  <- "Top-predators"
nedbr$X  <- "Decomposers"
herbi$X  <- "Herbivores"
primp$X  <- "Primary producers"
ni <- rbind(forest,
             mpred,
             tpred,
             nedbr,
             herbi,
             primp) 
```


```{r}
ni <- ni[ni$reg=="Norge",]
```

```{r}
yAxisTitle = "Index"
lowYlimit = 0
upperYlimit = 1.1
yStep = .2
minyear = 1980
maxyear = 2021
colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey")
legendPosition = "topleft"
legendInset = 0.03
horizontal = F
legendTextSize = 1.25
move = 0.1
```

```{r}
dat <- ni
  

  
dat2 <- aggregate(data=dat,
                    val~year+X,
                    FUN = function(x) quantile(x, c(0.025, .5, .975)))
  
dat2 <- do.call(data.frame, dat2)
  names(dat2)[3] <- "low"
  names(dat2)[4] <- "med"
  names(dat2)[5] <- "upp"
  
  
  ### PLOT meso-predators first first (I dont bother changing the name from Norway)
  
  Norge <- subset(dat2, X=="Meso-predators")
  
  
  
  # Order data (by the position of the lines)
  regOrder = c(
               "Primary producers",
               "Herbivores",
               "Nature Index Forest",
               "Decomposers",
               "Top-predators",
               "Meso-predators"
               )
  dat <- dat[order(match(dat$X,regOrder),dat$year),]
  
  # Create loop factors
  uniq1 <- unique(unlist(dat$year))
  uniq2 <- unique(unlist(dat$X))
```


```{r}
png("../output/indicatorPlots/englishPlots/skog/naturindekser.png", 
    units="in", width=12, height=7, res=300)

  # Plot windows par
par(mfrow=c(1,1), 
    mar=c(4.5,5.5,0,2))


  plot(
    Norge$med~Norge$year, 
    ylab=yAxisTitle,
    xlab="",
    main="",
    xlim=c(minyear, maxyear),
    ylim=c(lowYlimit, upperYlimit),
    cex.main=1,
    cex.lab=1.5,
    cex.axis=1.5,
    type="n", 
    frame.plot=FALSE,
    axes=FALSE
  )
  
  # Axis 1 options
  axis(side=1, at=c(minyear, Norge$year, maxyear), labels=c("",Norge$year, ""), cex.axis=1.5) 
  
  
  # Axis 2 options
  axis(side=2, at=seq(lowYlimit, upperYlimit, yStep), 
       labels=seq(lowYlimit, upperYlimit, yStep), 
       cex.axis=1.5)
  
  
  # Add lines
  lines(Norge$year+(move*(-2.5)), Norge$med, col=colours[6], lwd=2, lty=3) 
  
  # Save temp points for later addition to plot
  temppoints <- data.frame(year = Norge$year, med = Norge$med)
  
  
  
  
  
  
  
  # Add quantiles to plot
  for(i in 1:nrow(Norge)){
    arrows(Norge$year[i]+(move*(-2.5)),Norge$med[i],Norge$year[i]+(move*(-2.5)),Norge$upp[i], angle=90, length=0.05, col=colours[6], lwd=1)
    arrows(Norge$year[i]+(move*(-2.5)),Norge$med[i],Norge$year[i]+(move*(-2.5)),Norge$low[i], angle=90, length=0.05, col=colours[6], lwd=1)
    
  }   
  
  # Empty temporary points data frame
  temppoints3 <- data.frame()
  
  
  
  ### Then plot loop per region
  for(n in 1:(length(uniq2)-1)){
    
    # Subset for region i
    quants <- subset(dat2, X==uniq2[n])
    
    # Add lines
    lines(quants$year+move*(n-2.5), quants$med, col=colours[n], lwd=2, lty=3) 
    
    # Save temp points for later addition to plot
    temppoints2 <- data.frame(year = quants$year, med = quants$med, X = uniq2[n])
    temppoints3 <- rbind(temppoints3, temppoints2)
    
    # Add quantiles to plot
    for(i in 1:nrow(quants)){
      arrows(quants$year[i]+move*(n-2.5),quants$med[i],quants$year[i]+move*(n-2.5),quants$upp[i], angle=90, length=0.05, col=colours[n], lwd=1)
      arrows(quants$year[i]+move*(n-2.5),quants$med[i],quants$year[i]+move*(n-2.5),quants$low[i], angle=90, length=0.05, col=colours[n], lwd=1)
    }
    
  }
  
  # Add points for regions
  for(n in 1:(length(uniq2)-1)){
    temppoints4 <- temppoints3[temppoints3$X==uniq2[n],]
    points(temppoints4$year+move*(n-2.5),temppoints4$med, pch=21, bg=colours[n], cex=1.5)
  }
  
  # Add points for Norge
  points(temppoints$year+(move*(-2.5)),temppoints$med, pch=21, bg=colours[6], cex=1.5)
  
  # Add legend to plot
  legend(legendPosition, legendPositionY, legend = c(uniq2[6], uniq2[1:5]), col = c(colours[6], colours[1:5]), bg = c(colours), pch=16, lty=2,
         lwd=1.5, bty="n", inset=legendInset, title="", horiz = horizontal,
         cex=legendTextSize)
  
  
dev.off()
  
```


# LSK data

```{r, warning=F}
setwd("P:/41201042_okologisk_tilstand_fastlandsnorge_2020_dataanaly/FINAL/Indicator_values/Forest")

### National forest inventory (NFI) data (reduced, without Finnmark and above the treeline)
lsk <- read.csv("LSK_data_bootstrapped-reduced.csv", header=T,  row.names = 1)

# Subset NFI data
lsk <- lsk %>% dplyr::select(reg, year, ros, dw10, dw30, old_prop, blb,
                             biomass_trees, alien_trees, GRAN_PR, INTRO_GRAN_PR, FURU_PR, INTRO_FURU_PR,
                             BJORK_PR, OSP_PR, EIK_PR, EDELLAUV_PR, GRAAOR_PR, ANNET_LAUV_PR)

lsk$year <- as.numeric(as.character(lsk$year))

# Separate data files
ros <- lsk %>% dplyr::select(reg, year, ros) %>%
  dplyr::rename(val=ros)
#dw10 <- lsk %>% dplyr::select(reg, year, dw10) %>%
#  dplyr::rename(val=dw10)
dw30 <- lsk %>% dplyr::select(reg, year, dw30) %>%
  dplyr::rename(val=dw30)
old <- lsk %>% dplyr::select(reg, year, old_prop) %>%
  dplyr::rename(val=old_prop)
blb <- lsk %>% dplyr::select(reg, year, blb) %>%
  dplyr::rename(val=blb)

#biomasstrees <- lsk %>% dplyr::select(reg, year, biomass_trees) %>%

#  dplyr::rename(val=biomass_trees)
alientrees <- lsk %>% dplyr::select(reg, year, alien_trees) %>%
  dplyr::rename(val=alien_trees)

alientrees$val[alientrees$year==1996] <- NA # Needs adjustment in LSK script


```
```{r}
#source("indicator_plots2.R")
eval(parse("indicator_plots.R", encoding="UTF-8"))
eval(parse("indicator_plots2.R", encoding="UTF-8"))
eval(parse("indicator_plots4.R", encoding="UTF-8"))

```

# Functinally important species and structures
```{r}
summary(blb$val)
summary(blb$year)
summary(dw30$val)
summary(dw30$year)
summary(ros$val)
summary(ros$year)
summary(old$val)
summary(old$year)
```
##With regions
```{r, eval=F, include=FALSE}
png("../output/indicatorPlots/englishPlots/skog/FunctionallyImportant.png", 
    units="in", width=12, height=12, res=300)

# Plot windows par
par(mfrow=c(2,2), 
    mar=c(4.5,5.5,0,2))

#1
indicator_plot2(dataset = blb,
               yAxisTitle = "Bilberry cover (%)",
               lowYlimit = 0,
               upperYlimit = 13,
               yStep = 2,
               minyear = 1992,
               maxyear = 2021,
               colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey"),
               legendPosition = "left",
               legendInset = 0.2,
               move = 0.1,
               horizontal = F,
               legendTextSize = 1.25)
#2
indicator_plot2(dataset = dw30,
               yAxisTitle = bquote("Coarse woody debis " ~ (m^3 ~ ha^-1)),
               lowYlimit = 0,
               upperYlimit = 6,
               yStep = 1,
               minyear = 1992,
               maxyear = 2021,
               colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey"),
               legendPosition = "left",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)


#3
indicator_plot2(dataset = ros,
               yAxisTitle = bquote("Rowan-aspen-goat willow " ~ (m~3 ~ ha~-1)),
               lowYlimit = 0,
               upperYlimit = 13,
               yStep = 2,
               minyear = 1992,
               maxyear = 2021,
               colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey"),
               legendPosition = "top",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)

#4
indicator_plot2(dataset = old,
               yAxisTitle = "Biologically old forest (prop.)",
               lowYlimit = 0,
               upperYlimit = 0.25,
               yStep = 0.05,
               minyear = 1992,
               maxyear = 2021,
               colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey"),
               legendPosition = "top",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)
#dev.off()

```

## Without regions
```{r, eval=F, include=FALSE}
png("../output/indicatorPlots/englishPlots/skog/FunctionallyImportant_noRegions.png", 
    units="in", width=10, height=10, res=300)

# Plot windows par
par(mfrow=c(2,2), 
    mar=c(4.5,5.5,0,2))

#1
indicator_plot4(dataset = blb,
               yAxisTitle = "Bilberry cover (%)",
               lowYlimit = 0,
               upperYlimit = 13,
               yStep = 2,
               minyear = 1992,
               maxyear = 2021,
               colours = "dark grey",
               legendPosition = "left",
               legendInset = 0.2,
               move = 0.1,
               horizontal = F,
               legendTextSize = 1.25)
#2
indicator_plot4(dataset = dw30,
               yAxisTitle = bquote("Coarse woody debis " ~ (m^3 ~ ha^-1)),
               lowYlimit = 0,
               upperYlimit = 4,
               yStep = 1,
               minyear = 1992,
               maxyear = 2021,
               colours = "dark grey",
               legendPosition = "left",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)


#3
indicator_plot4(dataset = ros,
               yAxisTitle = bquote("Rowan-aspen-goat willow " ~ (m~3 ~ ha~-1)),
               lowYlimit = 0,
               upperYlimit = 6,
               yStep = 2,
               minyear = 1992,
               maxyear = 2021,
               colours = "dark grey",
               legendPosition = "top",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)

#4
indicator_plot4(dataset = old,
               yAxisTitle = "Biologically old forest (prop.)",
               lowYlimit = 0,
               upperYlimit = 0.2,
               yStep = 0.05,
               minyear = 1992,
               maxyear = 2021,
               colours = "dark grey",
               legendPosition = "top",
               legendInset = -50,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)
dev.off()

```





# Alien trees
```{r}
summary(alientrees$val)
summary(alientrees$year)

```

```{r}
png("../output/indicatorPlots/englishPlots/skog/alienTrees.png", 
    units="in", width=12, height=7, res=300)

# Plot windows par
par(mfrow=c(1,1), 
    mar=c(4.5,5.5,0,2))

#1
indicator_plot2(dataset = alientrees,
               yAxisTitle = "Alien conifers (%)",
               lowYlimit = 0,
               upperYlimit = 7,
               yStep = 2,
               minyear = 2000,
               maxyear = 2019,
               colours = c("#FFB25B", "#2DCCD3", "#004F71", "#7A9A01", "#93328E", "dark grey"),
               legendPosition = "top",
               legendInset = 0,
               move = 0.1,
               horizontal = T,
               legendTextSize = 1.25)
dev.off()
```








