---
title: "Vurdering av indikatoregnethet - for indikatoreksperter"
author: ""
date: ""
output: pdf_document

knit: (function(input_file, encoding) {
  out_dir <- '../data';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'sjekkliste.pdf'))})
---

Dette sjemaet fylles ut av indikatorreksperter. 


\def\LayoutTextField#1#2{% label, field
  #2%
}


\begin{Form}
    Indikatornavn: \TextField[width=10cm]{Indikatornavn}
    \\\\
    Utfyller(e): \TextField[multiline=true, width=10cm,height=1cm]{Tilstede}
    \\\\
    Dato: \TextField[width=3cm]{Dato}\\
    \\
    Kort om indikatorens betydning i økosystemet og økologiske konsekvenser ved redusert indikatorverdi (inkluder gjerne referanser)\\\\
     \TextField[multiline=true, width=\linewidth,height=4cm,invisible=true]{a}
     \\\\
      \CheckBox{Indikatoren påvirkes betraktelig av menneskelig aktivitet, og 
      denne responsen blir ikke overskygget av den naturlige variasjonen i 
      indikatoren}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{b}\\\\
      \CheckBox{Vi har kontroll på at variasjonen vi innfører gjennom 
      beregningene våre, for eksempel ved ekstrapoleringer, og er sikre
      på at denne variasjonen ikke overskygger eller systematisk 
      styrer verdien av indikatoren}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{c}\\\\
      \CheckBox{Indikatoren representerer en unik side ved økosystemet som 
      ikke fanges opp av noen av de andre indikatorene}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{d}
     \\\\
      \CheckBox{Metoden for beregning av indikatorverdier er godt dokumentert 
      og beregningene er reproduserbare}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{e}
     \\\\
      \CheckBox{Fastsetting av referanseverdier (0, 1) og grenseverdier for 
      GØT er godt faglig begrunnet, dokumentert og gjennomdiskutert med flere 
      fagfeller}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{f}
     \\\\
      \CheckBox{Indikatoren lar seg tilskrive en eller flere av de syv 
      definerte økosystemegenskapene}\\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{g}\\\\
      \CheckBox{Data som trengs for å støtte indikatoren er
       tilgjengelig eller kunne gjøres tilgjengelig ved etterspørsel 
       på en kostnadseffektiv måte}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{h}\\\\
      \CheckBox{Data som trengs for å støtte indikatoren er 
      godt dokumentert og av kjent kvalitet}
      \\
    Kommentar: \\\\
     \TextField[multiline=true, width=\linewidth,height=4cm]{i}
     \\\\
     Generelle kommentarer: 
     \\\\
     \TextField[multiline=true, width=\linewidth,height=6cm]{j}
     \\\\
    
     
     
    
\end{Form}
